export const ROUTES = {
    root: '/',
    login: '/login',
    register: '/register',
    recover: '/recover',
    dashboard: '/dashboard',
    quickInsert: '/quick-insert',
    jobs: '/jobs',
    orders: '/orders',
    activities: '/activities',
    customers: '/customers',
    suppliers: '/suppliers',
    resources: '/resources',
    resourceSkill: '/resource-skill',
    purchaseInvoice: '/purchase-invoice',
    purchaseInvoiceActivity: '/purchase-invoice-activity',
    salesInvoices: '/sales-invoices',
    scheduledPayments: '/scheduled-payments',
    scheduledValues: '/scheduled-values',
    skills: '/skills',
    typeOfPayments: '/type-of-payments',
    users: '/users',
    timesheet: '/timesheet',
    report: '/report',
}